#ifndef PROTOCOL_H
#define PROTOCOL_H

typedef unsigned int uint;

//信息类型的枚举值
enum ENUM_MSG_TYPE {
    ENUM_MSG_TYPE_MIN = 0,  //设置一个最小值
    ENUM_MSG_TYPE_REGIST_REQUEST,
    ENUM_MSG_TYPE_REGIST_RESPOND,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPOND,
    ENUM_MSG_TYPE_FIND_USER_REQUEST,
    ENUM_MSG_TYPE_FIND_USER_RESPOND,
    ENUM_MSG_TYPE_ONLINE_USER_REQUEST,
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_RESPOND,
    ENUM_MSG_TYPE_ADD_FLUSH_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FLUSH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DELETE_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUEST,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_TYPE_MKDIR_REQUEST,
    ENUM_MSG_TYPE_MKDIR_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_DEL_FILE_REQUEST,
    ENUM_MSG_TYPE_DEL_FILE_RESPOND,
    ENUM_MSG_TYPE_RENAME_FILE_REQUEST,
    ENUM_MSG_TYPE_RENAME_FILE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_BREAKPOINT_REQUEST,   // 断点续传请求
    ENUM_MSG_TYPE_UPLOAD_FILE_BREAKPOINT_RESPOND,  // 断点续传响应
    ENUM_MSG_TYPE_MAX = 9999,   //设置最大值
};

struct PDU{ //协议数据单元
    uint uiTotalLen;    //数据的总长度
    uint uiMsgLen;      //柔性数组的长度（消息长度）
    uint uiType;        //类型
    char caData[64];    //参数    数据长度小于信息长度的就放到参数里
    char caMsg[];       //消息
};

struct FileInfo{
    char caName[32]; //文件名
    uint uiType;    //文件类型
};

//每次发送消息的时候都要使用到结构体PDU
//所以设计一个函数 初始化协议数据单元的函数
PDU* mkPDU(uint uiMsgLen = 0);

#endif // PROTOCOL_H
